In [1]:
import tabs
import pandas as pd

# Read in Galveston Bay data from TABS website

You can change any of the code in these cells, and add your own cells and do more things. 

Because data from different stations is gathered at different rates, it is all interpolated to 15 minutes.

To run this notebook, click

> Cell > Run All

After it has finished running, the data can be found on the tab to the left called "Home". Click on that tab, click on the little box in front of `data.csv` and then select "Download" to download the data to your computer.

Change the inputs in the following cell:

In [2]:
# List of stations in Galveston Bay
stations = ['FISH', 'MIDG', 'TRIN', 'BOLI', 'OLDR', '8771486','8770613','8771013','8771341','8770777','g06010']

# 'year-month-day' for start and end dates
startdate = '2017-9-1'
enddate = '2017-10-1'

In [3]:
# you can ignore the warnings!

df = pd.DataFrame()

# loop over stations to read in data
for station in stations:
    dft = tabs.read(station, startdate, enddate, resample=('15T', 0, 'instant', False))
    df = pd.concat([df,dft],axis=1)

HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR
HTTP Error 500: INTERNAL SERVER ERROR

/Users/kthyng/miniconda3/envs/cart/lib/python3.7/site-packages/pandas/core/missing.py:159: FutureWarning: Converting timezone-aware DatetimeArray to timezone-naive ndarray with 'datetime64[ns]' dtype. In the future, this will return an ndarray with 'object' dtype where each element is a 'pandas.Timestamp' with the correct 'tz'.
	To accept the future behavior, pass 'dtype=object'.
	To keep the old behavior, pass 'dtype="datetime64[ns]"'.
  result = np.empty_like(np.asarray(xvalues), dtype=np.float64)

In [4]:
df

,FISH: Salinity,FISH: Depth [m],FISH: WaterT [deg C],MIDG: Salinity,MIDG: Depth [m],MIDG: WaterT [deg C],TRIN: Salinity,TRIN: Depth [m],TRIN: WaterT [deg C],TRIN: Dissolved oxygen concentration [mgl],...,8770777: Gust [m/s] (air),8770777: North [m/s] (air),8770777: RelH [%],8770777: Speed [m/s] (air),"8770777: Water Level [m, MSL]",8770777: WaterT [deg C],g06010: Speed [cm/s] (water),g06010: Dir [deg T] (water),g06010: Along [cm/s] (water),g06010: Across [cm/s] (water)
2017-09-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09-01 00:15:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.15,-0.905,NaN,1.90,0.575,24.60,127.00,66.0,-123.740,-28.570
2017-09-01 00:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.60,-1.060,NaN,1.90,0.570,24.60,117.05,63.5,-112.795,-31.255
2017-09-01 00:45:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.05,-0.565,NaN,1.10,0.560,24.60,120.80,62.0,-115.520,-35.320
2017-09-01 01:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.60,-0.410,NaN,1.00,0.550,24.60,113.00,64.0,-109.135,-29.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-30 23:00:00+00:00,3.490921,2.082886,28.311157,11.255797,2.981628,28.527222,2.063563,1.358337,28.002625,7.778163,...,4.10,-2.800,NaN,3.20,0.190,27.70,87.10,74.5,-86.800,-6.850
2017-09-30 23:15:00+00:00,3.455164,2.073776,28.290100,11.082943,2.969818,28.529053,2.096632,1.344421,27.921371,7.736510,...,4.70,-2.585,NaN,3.10,0.180,27.65,83.30,73.0,-82.845,-8.705
2017-09-30 23:30:00+00:00,3.419407,2.064667,28.269043,10.910089,2.958008,28.530884,2.129701,1.330505,27.840118,7.694856,...,4.40,-2.570,NaN,3.10,0.160,27.60,85.90,72.5,-85.320,-9.735
2017-09-30 23:45:00+00:00,3.383649,2.055557,28.247986,10.737235,2.946198,28.532715,2.162770,1.316589,27.758865,7.653203,...,3.65,-2.255,NaN,2.65,0.145,27.60,86.00,73.0,-85.530,-8.990
2017-10-01 00:00:00+00:00,3.347892,2.046448,28.226929,10.564380,2.934387,28.534546,2.195839,1.302673,27.677612,7.611549,...,3.80,-2.320,NaN,2.80,0.120,27.60,85.75,73.5,-85.330,-8.185

Data is saved to a csv file.

In [5]:
df.to_csv('data.csv')